filebeat.inputs:
  - type: filestream
    id: orders-logs-input
    paths:
      - '/var/lib/docker/containers/*/*-json.log'

    processors:
      - add_docker_metadata: ~
      - drop_event:
          when:
            not:
              equals:
                container.name: "orders"

    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log
    json.overwrite_keys: true

    scan_frequency: 5s
    harvester_limit: 5
    close.timeout: 20s

output.logstash:
  hosts: ["logstash_orders:5044"]

logging.level: info