"""add order status enum

Revision ID: 5ce65ba424c6
Revises: 5baf2e3d0ff6
Create Date: 2026-04-08 14:40:47.090702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce65ba424c6'
down_revision: Union[str, Sequence[str], None] = '5baf2e3d0ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE orderstatus AS ENUM('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'RECEIVED', 'CANCELED')")

    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'RECEIVED', 'CANCELED', name='orderstatus'),
               existing_nullable=False,
               postgresql_using='UPPER(status)::orderstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'RECEIVED', 'CANCELED', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.execute("DROP TYPE IF EXISTS orderstatus CASCADE")
    # ### end Alembic commands ###
