input {
  beats {
    port => 5044
    host => "0.0.0.0"
    ecs_compatibility => disabled
  }
}

filter {
  if [container][name] == "orders" {
    if [message] =~ /^\s*\{/ {
      json {
        source => "message"
        add_tag => ["docker_parsed"]
    }
  }

    if "docker_parsed" in [tags] and [log] =~ /^\s*\{/ {
      json {
        source => "log"
        add_tag => ["app_parsed"]
      }
    }

    if ![service] {
      drop {}
    }

    mutate {
      remove_field => [
        "agent", "host", "ecs", "input", "event", "tags", "@version", "beat", "offset", "source", "stream",
        "time", "docker_container", "container_id", "log.file", "log", "container"
      ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch-orders:9200"]
    index => "orders-logs-%{+YYYY.MM.dd}"
    ecs_compatibility => disabled
  }
}