apiVersion: 1

datasources:
  - name: Prometheus-Orders
    type: prometheus
    uid: prometheus-orders
    access: proxy
    url: http://prometheus_orders:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
